//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportApp.Data_Component
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickUpTable()
        {
            this.EmpRoutes = new HashSet<EmpRoute>();
            this.EmpRoutes1 = new HashSet<EmpRoute>();
        }
    
        public int EntryID { get; set; }
        public string PickUpPoint { get; set; }
        public Nullable<int> RouteNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpRoute> EmpRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpRoute> EmpRoutes1 { get; set; }
        public virtual RouteTable RouteTable { get; set; }
    }
}
