//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportApp.Data_Component
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RouteTable()
        {
            this.PickUpTables = new HashSet<PickUpTable>();
        }
    
        public int RouteNo { get; set; }
        public string RouteName { get; set; }
        public int FinalPrice { get; set; }
        public string RouteImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickUpTable> PickUpTables { get; set; }
    }
}
