//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportApp.Data_Component
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransportEntities : DbContext
    {
        public TransportEntities()
            : base("name=TransportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmpRoute> EmpRoutes { get; set; }
        public virtual DbSet<EmpTable> EmpTables { get; set; }
        public virtual DbSet<PickUpTable> PickUpTables { get; set; }
        public virtual DbSet<RouteTable> RouteTables { get; set; }
    }
}
